---
- name: Running PMM Data Container without Security ( unprotected )
  docker_container:
    name: pmm-server
    insecure_registry: true
    image: "percona/pmm-server:{{ pmm_server_version }}"
    state: started
    volumes_from:
    - pmm-data
    env: "{{ __pmm_server_env }}"
    ports:
    - "80:80"
    restart_policy: always
