---
- name: Uninstalling PMM Data Container
  docker_container:
    name: pmm-server
    image: "percona/pmm-server:{{ pmm_server_version }}"
    state: absent
    volumes:
    - /opt/prometheus/data
    - /opt/consul-data
    - /var/lib/mysql
    - /var/lib/grafana
    command: /bin/true

- name: Removing cert files directory used by PMM server
  file:
    path: /etc/pmm-certs
    state: absent
